# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AwIGcn7xj0GgElo6c6MqnZ2aYbKZNTSb
"""

install matplotlib

import matplotlib.pyplot as plt

def carbon_footprint_calculator():
    print("Merhaba! Karbon Ayak İzi Hesaplayıcıya Hoş Geldiniz.")
    print("Haydi soruları cevaplayarak karbon ayak izinizi hesaplayalım.\n")

    questions = [
        "Ayda kaç saat uçak yolculuğu yapıyorsunuz?",
        "Haftada kaç kez çamaşır makinesi kullanıyorsunuz?",
        "Haftada kaç kez bulaşık makinesi kullanıyorsunuz?",
        "Günlük telefon kullanım süreniz nedir? (saat)",
        "Günde kaç adet sigara içiyorsunuz?",
        "Günlük otobüs yolculuğu mesafeniz nedir? (km)",
        "Günde kaç saat TV izliyorsunuz?",
        "Günlük elektrik tüketiminiz nedir? (kWh)",
        "Günlük kullanılan plastik su şişesi sayısı nedir?",
        "Günlük benzin tüketiminiz nedir? (litre)",
        "Metreküp doğalgaz başına aylık tüketiminiz nedir? (m^3)",
        "Haftada fırında yemek pişirme süreniz nedir?(saat)",
        "Günde kaç saat uyursunuz(saat)",
        "Günde kaç fincan kahve içersiniz? ",
        "Günlük bisiklet kullanım süreniz nedir? (saat)",
        "Günlük duş alma süreniz nedir? (dakika)",
        "Günlük şarj ettiğiniz elektronik cihaz sayısı nedir? (adet)",
        "Günlük kitap okuma süreniz nedir? (saat)",
        "Günlük sebze tüketiminiz nedir? (kg)",
        "Günlük temizlik malzemesi kullanımınız nedir? (litre)",
        "Günlük ofis malzemesi kullanımınız nedir? (adet)",
        "Günlük diş fırçalama sayınız nedir? (adet)",
        "Günlük bilgisayar kullanım süreniz nedir? (saat)",
        "Günlük aydınlatma kullanım süreniz nedir? (saat)",
        "Günlük yemek pişirme süreniz nedir? (saat)"
    ]

    answers = []

    for question in questions:
        answer = float(input(question + " "))
        answers.append(answer)

    carbon_footprints = [
        answers[0] * 90,   # Uçak kullanımı
        answers[1] * 0.1225, # Çamaşır makinası kullanımı
        answers[2] * 1.61538446154,   # Bulaşık makinası kullanımı
        answers[3] * 63,   # Telefon kullanımı
        answers[4] * 0.014,# Sigara kullanımı
        answers[5] * 0.04, # Otobüs kullanımı
        answers[6] * 9.2,  # TV kullanımı
        answers[7] * 0.447,# Elektrik tüketimi
        answers[8] * 82.8,# Plastik su şişesi
        answers[9] * 2.3, # Benzin tüketimi
        answers[10] * 2.4, # Metreküp doğalgaz başına
        answers[11] * 0.4, # Fırında yemek pişirme
        answers[12] * 11,   # Uyurken harcanan CO2
        answers[13] * 0.4,  # Bir fincan kahve için kullanılan kahve miktarı
        answers[14] * 0.02, # Bisiklet kullanımı
        answers[15] * 0.1,  # Duş alma
        answers[16] * 0.5,  # Elektronik cihaz şarjı
        answers[17] * 0.01, # Kitap okuma
        answers[18] * 0.3,  # Sebze tüketimi
        answers[19] * 0.05, # Temizlik malzemesi kullanımı
        answers[20] * 0.1,  # Ofis malzemesi kullanımı
        answers[21] * 0.005,# Diş fırçalama
        answers[22] * 0.3 ,  # Bilgisayar kullanımı
        answers[23] * 0.02,  # Aydınlatma kullanımı
        answers[24] * 0.1,  # Yemek pişirme
    ]

    total_carbon_footprint = sum(carbon_footprints)

    print("\nKarbon Ayak İziniz:", total_carbon_footprint, "kg CO2")

    return carbon_footprints, questions

def draw_pie_chart(carbon_footprints, questions):
    labels = [question.split(' ', 1)[1] for question in questions]
    explode = [0.1] * len(labels)

    plt.figure(figsize=(10, 8))
    plt.pie(carbon_footprints, labels=labels, autopct='%1.1f%%', startangle=140, explode=explode)
    plt.title("Karbon Ayak İzi Dağılımı")
    plt.show()

if __name__ == "__main__":

    carbon_footprints, questions = carbon_footprint_calculator()


    draw_pie_chart(carbon_footprints, questions)
